### PR TITLE
Implement SHEEPIT_MEMORY_LIMIT to fix #1

### LINKED ISSUE #1: Image does not recognize Docker memory limits
If a memory limit is set with `--memory`, the container will exceed this and cause the process to be killed.

Ideally the container would either detect this memory limit and use the value manually, or allow the Sheepit memory limit to be set from the environment variables.

### PR DESCRIPTION
**Pull request by Xalaxis**
Hi @fkrauthan , this is my solution to the memory limit issue.  When set, the environment variable `SHEEPIT_MEMORY_LIMIT` can be used to limit the amount of memory usable by the SheepIt client, otherwise it defaults to unlimited (actually 999GB).

This PR fixes #1 .

### CODE REVIEW

**Comment by Xalaxis** [comment]
There's also an addition to the .gitignore to ignore .jar files, to ease certain testing cases.

**Comment by Xalaxis** [comment]
Hi @fkrauthan any chance to review this?  I'd like to use this feature on my personal machines and don't want to switch to using a fork 😜

**Comment by fkrauthan** [comment]
Oh I am very sorry I totally forgot about this. The change looks good.

**Comment by fkrauthan** [comment]
@Xalaxis new images are published. `latest` and `6.2020.0.1` both contain your change. Thanks again very much for your contribution.

**Comment by Xalaxis** [comment]
No problem, cheers for merging 😄 ❤️

**Pull request merged**
